name: Build test NVIDIA driver patches

on:
  schedule:
     - cron: "0 0 1,8,15,22,28 * *"
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kernel: [legacy, ubuntu-lts, ubuntu-lts-hwe, ubuntu-lts-hwe-edge, ubuntu-lts-preview]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build against the ${{ matrix.kernel }} kernel
        run: make test-${{ matrix.kernel }}
